Added support for handler tag options and subscriber options
fmasa/messenger pull request #17
Opened 2022-11-10 04:12 UTC by tg666

Added support for all handler options according to the Symfony [documentation](https://symfony.com/doc/current/messenger.html#manually-configuring-handlers).

```neon
# ...
tags:
    messenger.messageHandler:
        # currently supported:
        bus: bus_name
        alias: alias_name
        
        # newly supported:
        priority: 10
        method: myHandleMethod
        handles: App\MyMessage
        from_transport: async
```

```php

final class MyMessageSubscriber implements MessageSubscriberInterface
{
    /**
     * @return iterable<string, array{method: string, from_transport: string}>
     */
    public static function getHandledMessages(): iterable
    {
        yield MyMessage::class => [
            # currently supported:
            'method' => 'myHandleMethod',
            
            # newly supported:
            'priority' => 10,
            'bus' => 'bus_name',
            'from_transport' => 'memory1',
        ];
    }
 }
```

2022-11-10 09:56 UTC, fmasa commented
Hi, first of all, thank you for the PR!
I didn't have time for deep dive yet, but it looks really well implemented and tested :slightly_smiling_face: 

Could you rebase your changes onto master? There were some CI issues in master.

I would like to do a proper code review on Saturday. :slightly_smiling_face:

2022-11-10 20:00 UTC, tg666 commented
Hi,
I did a rebase on the master and fixed phpstan errors in my changes.
Everything should go through with no problem 🙂 

Thank you

2022-12-14 13:45 UTC, fmasa requested changes
Hi, sorry for the fairly late review. I like these changes. Please check the comments, these are just small improvements necessary for this to merge.

Otherwise great job! I'm looking forward for getting this finished :slightly_smiling_face:

2022-12-14 13:45 UTC, fmasa commented on src/Messenger/DI/MessengerExtension.php
> +        if ($type instanceof ReflectionUnionType) {
We should add test for union types (see code coverage https://coveralls.io/builds/54132613/source?filename=src%2FMessenger%2FDI%2FMessengerExtension.php#L434)

2022-12-15 04:26 UTC, tg666 commented
Hi, thanks for your review!
I have implemented both of your comments + fixed the PHPUnit warning `assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.`, which was already there.

2022-12-15 21:46 UTC, tg666 commented
@fmasa I updated the minimum required version of `nette/di` from `3.0.1` to `3.0.6` because the previous version had a problem with calculating the continer checksum (it couldn't work with union types).

[3.0.1](https://github.com/nette/di/blob/v3.0.1/src/DI/DependencyChecker.php#L166) - the method `Reflection::getParameterType()` used - it throws an exception is a type is union.
[3.0.6](https://github.com/nette/di/blob/v3.0.6/src/DI/DependencyChecker.php#L174) - the method `Reflection::getParameterTypes()` used.

2023-03-16 20:37 UTC, fmasa approved these changes

2023-03-16 20:37 UTC, merged

2023-07-31 22:51 UTC, tg666 commented
@fmasa Hi, would be possible to make a new tag since these changes are already in the master?

2023-08-04 09:54 UTC, fmasa commented
@tg666 Hi, it's now released as [2.1.0](https://github.com/fmasa/messenger/releases/tag/2.1.0)